
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\zolech\Documents\Github\Tkinter-Designer\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1024x600")
window.configure(bg = "#232323")


canvas = Canvas(
    window,
    bg = "#232323",
    height = 600,
    width = 1024,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    288.0,
    49.0,
    anchor="nw",
    text="GPS Location",
    fill="#D9D9D9",
    font=("Roboto", 15 * -1)
)

canvas.create_text(
    288.0,
    434.0,
    anchor="nw",
    text="GPS Output",
    fill="#D9D9D9",
    font=("Roboto", 15 * -1)
)

canvas.create_text(
    663.0,
    49.0,
    anchor="nw",
    text="Bucket Location",
    fill="#D9D9D9",
    font=("Roboto", 15 * -1)
)

canvas.create_text(
    42.0,
    84.0,
    anchor="nw",
    text="COM Port",
    fill="#D9D9D9",
    font=("Roboto", 15 * -1)
)

canvas.create_text(
    754.0,
    398.0,
    anchor="nw",
    text="Close!",
    fill="#D9D9D9",
    font=("Roboto", 15 * -1)
)

canvas.create_text(
    425.0,
    17.0,
    anchor="nw",
    text="Dig Detect Desktop",
    fill="#D9D9D9",
    font=("Roboto Medium", 20 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    190.5,
    95.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=145.0,
    y=84.0,
    width=91.0,
    height=20.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=145.0,
    y=330.0,
    width=91.0,
    height=22.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=42.0,
    y=281.0,
    width=91.0,
    height=22.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=42.0,
    y=246.0,
    width=91.0,
    height=22.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=44.0,
    y=330.0,
    width=91.0,
    height=22.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=45.0,
    y=117.0,
    width=91.0,
    height=22.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=145.0,
    y=119.0,
    width=91.0,
    height=22.0
)

canvas.create_text(
    42.0,
    166.0,
    anchor="nw",
    text="GPS Port",
    fill="#D9D9D9",
    font=("Roboto", 15 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    190.5,
    177.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=145.0,
    y=166.0,
    width=91.0,
    height=20.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat"
)
button_7.place(
    x=42.0,
    y=199.0,
    width=91.0,
    height=22.0
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_8 clicked"),
    relief="flat"
)
button_8.place(
    x=145.0,
    y=199.0,
    width=91.0,
    height=22.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    438.0,
    234.0,
    image=image_image_1
)

canvas.create_rectangle(
    663.0,
    84.0,
    963.0,
    384.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    145.0,
    246.0,
    167.0,
    268.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    145.0,
    281.0,
    167.0,
    303.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    850.0,
    398.0,
    872.0,
    420.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    288.0,
    464.0,
    963.0,
    579.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    44.0,
    389.0,
    234.0,
    579.0,
    fill="#D9D9D9",
    outline="")
window.resizable(False, False)
window.mainloop()
